name: steam-deploy

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            path: 'mod'

      - name: cleanup-repo
        run: |
            rm -rf mod/.git
            rm -rf mod/.github/workflows
            rm -rf mod/.github
            rm -rf mod/.gitignore
            rm -rf mod/.gitattributes
            rm -rf mod/README.md

      - name: steam-workshop-upload
        uses: m00nl1ght-dev/steam-workshop-deploy@v3
        continue-on-error: true
        with: 
          appId: 294100 # Game's Steam App ID
          publishedFileId: 3008534396 # Your mod's Steam Workshop ID
          path: 'mod' # Path to your mod's folder from repository root
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf:  ${{ secrets.STEAM_CONFIG_VDF }}
          changeNote: ${{ github.event.head_commit.message }}
